In [69]:
# import GFA code and data Y, parameters from test data
source("CCAGFA.R")
source("data.r")

# data Y, factors K and rank R now available

In [70]:
# set parameters to GFA
opts <- getDefaultOpts()
opts$R <- 3
opts$dropK <- FALSE

In [71]:
# run
GFA(Y, K, opts)

[1] "The rank corresponds to full rank solution."
[1] "Iteration: 1 / cost: -15249.2797173797 / K 7"
[1] "Iteration: 2 / cost: -5063.69599546602 / K 7"
[1] "Iteration: 3 / cost: -3760.37458135377 / K 7"
[1] "Iteration: 4 / cost: -3433.04225184838 / K 7"
[1] "Iteration: 5 / cost: -3331.45456562996 / K 7"
[1] "Iteration: 6 / cost: -3306.54596133585 / K 7"
[1] "Iteration: 7 / cost: -3299.90110033502 / K 7"
[1] "Iteration: 8 / cost: -3297.59618804174 / K 7"
[1] "Iteration: 9 / cost: -3296.51494406506 / K 7"
[1] "Iteration: 10 / cost: -3295.9004792349 / K 7"
[1] "Iteration: 11 / cost: -3295.49708081519 / K 7"
[1] "Iteration: 12 / cost: -3295.18712144588 / K 7"
[1] "Iteration: 13 / cost: -3294.93752695074 / K 7"
[1] "Iteration: 14 / cost: -3294.7292146441 / K 7"
[1] "Iteration: 15 / cost: -3294.55217352455 / K 7"
[1] "Iteration: 16 / cost: -3294.39929751208 / K 7"
[1] "Iteration: 17 / cost: -3294.26596095128 / K 7"
[1] "Iteration: 18 / cost: -3294.14861538982 / K 7"
[1] "Iteration: 19 / cost

$W
$W[[1]]
             [,1]       [,2]          [,3]          [,4]          [,5]
 [1,] -0.01763115 -1.0342761 -0.0022480091 -1.074195e-06 -1.2175931142
 [2,] -0.53059508 -0.7577735 -0.0016890219 -1.961268e-06 -0.1177857928
 [3,] -0.55260080 -0.2771759 -0.0007204571 -1.336541e-06 -0.0001624283
 [4,] -0.08602593  0.9288395 -0.0005634845  2.602762e-06 -0.5244909296
 [5,]  0.21924373  1.0249912  0.0008513843  4.228428e-07  0.3331219624
 [6,] -0.05668776  0.2197437 -0.0027945015 -2.198878e-07  0.7633668286
 [7,] -0.03471103 -1.1787962  0.0006698443  9.850972e-07 -1.0289947701
 [8,]  0.06506653 -0.2131914 -0.0007603984 -3.863012e-06  0.2691153291
 [9,] -0.08174196  0.1870335 -0.0007725440  1.334344e-06 -0.0145333902
[10,] -0.61338859  0.9280967  0.0017821586  1.839918e-06 -0.0322488577
               [,6]        [,7]
 [1,]  1.649563e-04 -0.47975045
 [2,]  4.311081e-05 -0.88755838
 [3,]  3.631340e-05 -0.69949999
 [4,] -5.659195e-05  0.91750639
 [5,]  2.128669e-04 -0.00324949
 [6,]  1.783820e-04 -0.03417026
 [7,]  2.688113e-05  0.66631132
 [8,] -5.806838e-05 -1.85641471
 [9,]  1.122941e-04  0.61043585
[10,] -2.381989e-05  0.53303035

$W[[2]]
            [,1]          [,2]        [,3]          [,4]         [,5]
 [1,]  0.5741651  6.204972e-04  0.03874499  2.011753e-06  0.043179318
 [2,] -0.1623511 -4.549986e-04  0.15572304  2.906646e-06 -1.390102950
 [3,]  0.5828043 -6.724858e-05  0.85042609 -1.729056e-06  2.103540403
 [4,]  1.4545705  1.158354e-04 -0.25089575 -1.264737e-06 -1.632310325
 [5,]  0.2383756 -8.761885e-05  0.51299997 -1.215819e-06  1.339672299
 [6,] -0.6643152  2.591311e-04  0.36781375  2.658430e-06 -0.719929045
 [7,]  0.3383148  1.177261e-05 -1.17843207  9.004454e-07 -0.724143192
 [8,] -0.7523052  3.848528e-04  0.40751153 -1.231414e-06  0.008617761
 [9,] -0.6922645 -4.118299e-04 -0.13879502 -5.110504e-07 -0.920340286
[10,] -0.7707259  4.408755e-04  0.29767494 -1.318865e-06 -0.759866450
             [,6]       [,7]
 [1,] -0.14401955  1.1514889
 [2,]  0.43760556  1.1866547
 [3,] -0.34473479 -0.3105723
 [4,]  0.81471802 -0.7431843
 [5,]  1.95682492 -0.2757785
 [6,]  0.21505295  1.1174286
 [7,] -1.33845590  0.3197656
 [8,]  0.91062059 -0.7491797
 [9,]  0.07356994 -0.5870893
[10,] -0.16359845 -0.9669435

$W[[3]]
             [,1]        [,2]          [,3]          [,4]        [,5]
 [1,]  0.74388817 -0.50559542  0.0004109364 -1.456455e-06  0.47046978
 [2,] -0.18401865  0.58488836 -0.0012079122  1.758235e-06  0.09286321
 [3,] -0.03009908  0.36432811  0.0028146047 -1.266390e-06 -0.20135910
 [4,]  0.57860785  0.42552567 -0.0015754794  4.635676e-08 -0.62447866
 [5,]  0.04833309  0.02548889 -0.0003665117 -1.755111e-06  0.46109763
 [6,] -1.37538263  0.26077701 -0.0002457846 -2.121342e-06 -0.12907236
 [7,] -1.03603312 -1.13535091  0.0006439037  7.537397e-07 -0.36231867
 [8,]  0.34191558 -0.51860278 -0.0004914820 -6.125462e-07 -0.39394251
 [9,]  0.67659354  0.16360530 -0.0013551047 -1.201863e-06  0.65319935
[10,]  1.24173870 -1.56780023  0.0011263486 -6.261075e-06 -0.16925141
             [,6]       [,7]
 [1,] -0.15621657 -0.3563514
 [2,] -0.73665477  0.7028884
 [3,]  0.69969732 -0.8167998
 [4,]  0.57731033 -0.1393277
 [5,] -0.54612015 -0.8099180
 [6,] -1.12853063 -1.4562386
 [7,]  0.09118824  0.4936181
 [8,]  0.63432968 -0.1683683
 [9,]  1.22034829 -0.4108049
[10,] -0.60479537 -2.5393632


$covW
$covW[[1]]
              [,1]          [,2]          [,3]          [,4]          [,5]
[1,]  9.099315e-04  1.237447e-05  7.727913e-07 -2.705297e-10 -4.775269e-05
[2,]  1.237447e-05  9.274065e-04 -7.046133e-06  4.961239e-10 -9.091567e-05
[3,]  7.727913e-07 -7.046133e-06  4.809697e-05 -6.868961e-12 -4.764769e-07
[4,] -2.705297e-10  4.961239e-10 -6.868961e-12  9.167348e-06 -3.452526e-10
[5,] -4.775269e-05 -9.091567e-05 -4.764769e-07 -3.452526e-10  9.255391e-04
[6,] -3.335342e-07  1.670263e-07 -1.921278e-08  2.119711e-13  2.353194e-08
[7,]  9.724690e-06 -6.054499e-05  7.926178e-07  1.725195e-09  3.721574e-05
              [,6]          [,7]
[1,] -3.