In [1]:
# import GFA code and data Y, parameters from test data
source("CCAGFA.R")
source("data.r")

# data Y, factors K and rank R now available

In [2]:
# set parameters to GFA
opts <- getDefaultOpts()
opts$R <- R
opts$dropK <- FALSE
opts$verbose <- 2

In [3]:
# run GFA
res <- GFA(Y, K, opts)

[1] "NOTE: Optimization of the rotation is not supported for low rank model."
[1] "Iteration: 1 / cost: -21314.6123770879 / K 7"
[1] "Iteration: 2 / cost: -6998.87103550536 / K 7"
[1] "Iteration: 3 / cost: -5389.71263266168 / K 7"
[1] "Iteration: 4 / cost: -4518.18850131333 / K 7"
[1] "Iteration: 5 / cost: -3934.93660093718 / K 7"
[1] "Iteration: 6 / cost: -3638.67223308851 / K 7"
[1] "Iteration: 7 / cost: -3542.86378818897 / K 7"
[1] "Iteration: 8 / cost: -3512.42489779605 / K 7"
[1] "Iteration: 9 / cost: -3496.14747795561 / K 7"
[1] "Iteration: 10 / cost: -3483.18399204522 / K 7"
[1] "Iteration: 11 / cost: -3471.56150553503 / K 7"
[1] "Iteration: 12 / cost: -3460.82639176937 / K 7"
[1] "Iteration: 13 / cost: -3450.81256042836 / K 7"
[1] "Iteration: 14 / cost: -3441.42658160019 / K 7"
[1] "Iteration: 15 / cost: -3432.60240685275 / K 7"
[1] "Iteration: 16 / cost: -3424.28680063078 / K 7"
[1] "Iteration: 17 / cost: -3416.43479413878 / K 7"
[1] "Iteration: 18 / cost: -3409.00745040732 / 

In [4]:
# print results for reference
res

$W
$W[[1]]
               [,1]       [,2]        [,3]       [,4]          [,5]
 [1,]  3.663239e-04 -1.2891530 -1.17629389  2.2568426 -2.048416e-05
 [2,]  6.401815e-05 -0.1200695  0.14242496  0.1372293  6.135464e-04
 [3,]  1.598574e-04 -0.2823713 -0.33028299  0.3584497  5.257094e-05
 [4,] -1.865731e-04  0.1563678  0.04891629  1.8633550  1.520277e-04
 [5,] -1.112833e-04  0.1597829 -0.09289937 -0.2729067 -1.841604e-04
 [6,] -4.033374e-04 -1.6406056 -1.50146157  0.6555846  5.699494e-05
 [7,]  2.318320e-05 -0.8081232 -0.76032320 -0.4368015 -3.349867e-04
 [8,]  5.035606e-05  1.6810961 -0.31572962  0.2694431 -2.030402e-04
 [9,] -1.065639e-04  0.2959284 -1.03717509 -2.0038827  2.398814e-04
[10,] -1.055194e-04  0.9119326 -0.48876718 -1.5360746  1.170032e-04
               [,6]        [,7]
 [1,] -3.167353e-05  1.61834887
 [2,]  2.831569e-05 -0.81191948
 [3,]  1.315888e-04  0.72088137
 [4,] -7.552873e-05  0.01657578
 [5,]  1.934883e-05  1.18725911
 [6,] -1.408097e-04 -0.27825550
 [7,]  3.710458e-05 -1.37338956
 [8,] -1.203921e-05 -0.16702112
 [9,] -1.511057e-04  0.48376328
[10,]  3.573937e-05  1.05673273

$W[[2]]
             [,1]          [,2]        [,3]          [,4]        [,5]
 [1,]  1.39794265  1.419395e-04 -1.46795395 -1.737025e-03 -0.81978476
 [2,] -1.16257831 -5.051076e-05 -0.42160809  1.444564e-03 -0.06228478
 [3,] -0.30057366  1.720945e-05 -0.05378828 -6.692635e-04 -1.59037139
 [4,] -0.54066910  3.855964e-05  0.07192685  4.956335e-06 -1.47720375
 [5,]  2.53313435  5.983174e-05 -1.58870235  1.957947e-03  0.24628460
 [6,] -0.25881634  3.571112e-06  0.47804104  1.244671e-03 -2.14111897
 [7,] -0.26611992  9.208580e-05 -1.90335149  7.252911e-04 -0.91642847
 [8,] -1.44652033  2.372636e-04  0.86752551  9.543188e-04 -0.21287157
 [9,]  0.06800380  4.117559e-06 -1.06825192 -6.389627e-04 -0.34447885
[10,]  0.02481244 -6.502231e-05  0.11077416 -1.267125e-04 -0.13457025
               [,6]        [,7]
 [1,]  9.486850e-05  0.01182614
 [2,]  6.785806e-05  0.74531452
 [3,] -1.381229e-04  1.80416236
 [4,] -9.830792e-05 -1.32803758
 [5,] -3.844720e-05  0.30087338
 [6,]  6.939485e-05 -0.07340708
 [7,]  2.437102e-04  0.87152913
 [8,]  1.563403e-05 -0.73837912
 [9,] -1.898400e-04  0.38406624
[10,] -2.460998e-05  1.46569270

$W[[3]]
               [,1]          [,2]       [,3]        [,4]        [,5]
 [1,] -2.485531e-04  7.716978e-04 -0.6847141  1.11168386 -1.17280134
 [2,]  4.499484e-05 -7.071019e-04 -0.5652588 -0.06171364 -1.04059594
 [3,]  3.263271e-04  1.455025e-04  0.3998373 -1.67588119 -0.56072483
 [4,]  8.211612e-04 -5.192973e-04 -0.4921825 -0.78564904  0.01133116
 [5,]  5.228024e-04  1.044185e-04  0.9383428 -0.34268262 -1.09509920
 [6,] -2.806361e-05 -6.791408e-04 -0.7473710  0.35595847 -0.94775720
 [7,]  3.865390e-04 -3.194753e-04 -1.4644688  0.52303303 -1.42566062
 [8,] -2.235053e-04  5.799953e-05  0.2013140 -1.73166215 -1.19887538
 [9,] -7.465437e-04 -7.856945e-04 -0.2523747 -0.16540459 -0.24092325
[10,] -6.570473e-04 -4.022158e-04  0.7783301  1.45739418 -0.89306365
             [,6]        [,7]
 [1,]  0.04031532 -0.31280770
 [2,] -0.95105186 -0.54990139
 [3,]  0.17951906  0.18109623
 [4,]  0.05970502 -0.54854533
 [5,] -0.96722585  0.95668119
 [6,]  0.12938022 -0.50607082
 [7,]  0.35180383 -1.11027402
 [8,] -0.33291818  0.04645426
 [9,] -0.27659047 -0.15921030
[10,]  0.25638662  1.09593568


$covW
$covW[[1]]
              [,1]          [,2]          [,3]          [,4]          [,5]
[1,]  9.899702e-06 -2.319177e-07  6.927789e-07  1.945776e-06 -7.720252e-10
[2,] -2.319177e-07  1.047473e-03 -7.437122e-05  2.133676e-05  5.663473e-07
[3,]  6.927789e-07 -7.437122e-05  1.065658e-03  1.057308e-04 -8.140053e-07
[4,]  1.945776e-06  2.133676e-05  1.057308e-04  1.057086e-03  1.277175e-06
[5,] -7.720252e-10  5.663473e-07 -8.140053e-07  1.277175e-06  1.445667e-05
[6,]  5.839140e-09 -1.460816e-06  2.052406e-07 -9.811390e-08 -2.438234e-09
[7,] -1.263111e-07 -1.180468e-05 -3.154286e-05  2.374293e-05  4.534645e-08
              [,6]          [,7]
[1,]  5.

In [5]:
# convert W back to python (row major flattening)

# concatenate W
W <- do.call(rbind, res$W)
# W is transposed compared to paper
cat("import numpy as np\n\n")
cat("W_flat = np.array([", paste(c(W), collapse=",", sep=""), "])\n", sep="")
cat("W = W_flat.reshape((", ncol(W), ",", nrow(W), "))\n", sep = "")
cat("cost = np.array([", paste(res$cost,  collapse=",", sep=""), "])\n", sep="")

import numpy as np

W_flat = np.array([0.000366323922104649,6.40181459617959e-05,0.000159857376765492,-0.000186573101575556,-0.000111283255084977,-0.0004033373542749,2.31831979306423e-05,5.03560641361425e-05,-0.000106563922270378,-0.000105519396865078,1.39794265241356,-1.16257830718567,-0.300573664669502,-0.540669095588209,2.53313435067016,-0.25881633705863,-0.266119922782729,-1.4465203272971,0.0680037999436455,0.0248124401531043,-0.000248553138662066,4.49948381059073e-05,0.000326327131145114,0.00082116124939711,0.000522802435835067,-2.80636111125065e-05,0.000386539012077209,-0.000223505319697496,-0.000746543727064413,-0.000657047337586574,-1.28915300491366,-0.120069465078868,-0.282371289639988,0.156367802952971,0.159782891959229,-1.64060560617583,-0.808123214838274,1.68109614133741,0.295928429368508,0.911932579146191,0.000141939539211639,-5.05107580715267e-05,1.72094456056019e-05,3.85596428483221e-05,5.98317381046007e-05,3.57111185861101e-06,9.20858040524576e-05,0.000237263601550567,4