In [4]:
# import GFA code and data Y, parameters from test data
source("CCAGFA.R")
source("data.r")

# data Y, factors K and rank R now available

In [46]:
# set parameters to GFA
opts <- getDefaultOpts()
opts$R <- R
opts$dropK <- FALSE
opts$verbose <- 2

In [47]:
# run GFA
res <- GFA(Y, K, opts)

[1] "The rank corresponds to full rank solution."
[1] "Iteration: 1 / cost: -16517.6458371038 / K 7"
[1] "Iteration: 2 / cost: -5544.64500263645 / K 7"
[1] "Iteration: 3 / cost: -4068.52943140564 / K 7"
[1] "Iteration: 4 / cost: -3591.3984036685 / K 7"
[1] "Iteration: 5 / cost: -3390.82916357032 / K 7"
[1] "Iteration: 6 / cost: -3337.97672015284 / K 7"
[1] "Iteration: 7 / cost: -3326.0556247639 / K 7"
[1] "Iteration: 8 / cost: -3322.8377339265 / K 7"
[1] "Iteration: 9 / cost: -3321.63001104913 / K 7"
[1] "Iteration: 10 / cost: -3321.01935653628 / K 7"
[1] "Iteration: 11 / cost: -3320.60475790541 / K 7"
[1] "Iteration: 12 / cost: -3320.28898854295 / K 7"
[1] "Iteration: 13 / cost: -3320.03862332754 / K 7"
[1] "Iteration: 14 / cost: -3319.83265302892 / K 7"
[1] "Iteration: 15 / cost: -3319.66052568339 / K 7"
[1] "Iteration: 16 / cost: -3319.51343671523 / K 7"
[1] "Iteration: 17 / cost: -3319.38624111486 / K 7"
[1] "Iteration: 18 / cost: -3319.27515335653 / K 7"
[1] "Iteration: 19 / cost:

In [43]:
# print results for reference
res

$W
$W[[1]]
            [,1]          [,2]         [,3]          [,4]         [,5]
 [1,] -1.0344527 -1.638172e-04 -0.006618474 -0.0022676656 -1.215637507
 [2,] -0.7578762 -4.438504e-05 -0.514547621 -0.0017024819 -0.112747597
 [3,] -0.2771925 -3.753748e-05 -0.539505747 -0.0007259303  0.003928075
 [4,]  0.9290367  5.641264e-05 -0.100270846 -0.0005685027 -0.531343166
 [5,]  1.0251363 -2.104425e-04  0.220774302  0.0008576713  0.335033941
 [6,]  0.2197853 -1.778633e-04 -0.057998012 -0.0028178478  0.764202043
 [7,] -1.1789567 -2.757219e-05 -0.047444074  0.0006759328 -1.036443705
 [8,] -0.2133037  5.891414e-05  0.100544464 -0.0007676741  0.284236831
 [9,]  0.1870969 -1.122060e-04 -0.093377101 -0.0007787908 -0.019465688
[10,]  0.9283272  2.218822e-05 -0.621733227  0.0017981381 -0.036911289
              [,6]          [,7]
 [1,]  0.490242471  1.483020e-06
 [2,]  0.900141331  2.693551e-06
 [3,]  0.712495647  1.840157e-06
 [4,] -0.907126008 -3.542560e-06
 [5,] -0.004263538 -5.870615e-07
 [6,]  0.028199747  2.913147e-07
 [7,] -0.655825394 -1.330762e-06
 [8,]  1.848912260  5.268112e-06
 [9,] -0.606957051 -1.818976e-06
[10,] -0.514413126 -2.492970e-06

$W[[2]]
               [,1]        [,2]       [,3]        [,4]        [,5]       [,6]
 [1,]  6.233814e-04  0.14409034  0.5507403  0.03874007  0.03522221 -1.1653975
 [2,] -4.559638e-04 -0.43755518 -0.1800765  0.15573319 -1.40117598 -1.1657264
 [3,] -7.015513e-05  0.34456231  0.5816853  0.85044131  2.10852230  0.2735883
 [4,]  1.157039e-04 -0.81375756  1.4776818 -0.25096562 -1.62433594  0.7220622
 [5,] -8.760675e-05 -1.95659615  0.2459264  0.51302526  1.34184998  0.2593853
 [6,]  2.623315e-04 -0.21532347 -0.6835890  0.36784695 -0.73111758 -1.0905842
 [7,]  1.099929e-05  1.33855594  0.3295207 -1.17847724 -0.72525457 -0.3238963
 [8,]  3.885517e-04 -0.91072303 -0.7344867  0.40754115  0.01235141  0.7694395
 [9,] -4.127941e-04 -0.07363133 -0.6775386 -0.13879028 -0.91764501  0.6135998
[10,]  4.442959e-04  0.16342813 -0.7494120  0.29768801 -0.75414000  0.9931829
               [,7]
 [1,] -2.764066e-06
 [2,] -3.940707e-06
 [3,]  2.314530e-06
 [4,]  1.713279e-06
 [5,]  1.648593e-06
 [6,] -3.598015e-06
 [7,] -1.240672e-06
 [8,]  1.709319e-06
 [9,]  7.302386e-07
[10,]  1.832639e-06

$W[[3]]
             [,1]        [,2]        [,3]          [,4]        [,5]       [,6]
 [1,] -0.50575046  0.15640300  0.74797072  0.0004163871  0.47478911  0.3306020
 [2,]  0.58500820  0.73642645 -0.19929972 -0.0012245186  0.08795903 -0.6983868
 [3,]  0.36437198 -0.69946174 -0.01002216  0.0028527360 -0.19494849  0.8202317
 [4,]  0.42556781 -0.57688076  0.58651550 -0.0015975898 -0.62226704  0.1321032
 [5,]  0.02544944  0.54606258  0.06137846 -0.0003716383  0.46837579  0.8018413
 [6,]  0.26085054  1.12799595 -1.34915751 -0.0002489033 -0.11946794  1.4896123
 [7,] -1.13544267 -0.09163578 -1.04757069  0.0006536649 -0.37021352 -0.4638496
 [8,] -0.51870162 -0.63406953  0.34740413 -0.0004982302 -0.39303212  0.1635359
 [9,]  0.16358922 -1.21991859  0.68706086 -0.0013733860  0.65784848  0.3883463
[10,] -1.56824016  0.60528543  1.28777768  0.0011410388 -0.14750723  2.5014751
               [,7]
 [1,]  1.959274e-06
 [2,] -2.400831e-06
 [3,]  1.737732e-06
 [4,] -6.643650e-08
 [5,]  2.384760e-06
 [6,]  2.929620e-06
 [7,] -9.954766e-07
 [8,]  8.358514e-07
 [9,]  1.620823e-06
[10,]  8.509841e-06


$covW
$covW[[1]]
              [,1]          [,2]          [,3]          [,4]          [,5]
[1,]  9.277056e-04 -1.655059e-07  1.608952e-05 -7.109018e-06 -8.936918e-05
[2,] -1.655059e-07  1.034708e-05  3.027214e-07  1.920914e-08 -1.706490e-08
[3,]  1.608952e-05  3.027214e-07  9.107849e-04  7.769617e-07 -4.966599e-05
[4,] -7.109018e-06  1.920914e-08  7.769617e-07  4.850464e-05 -5.052466e-07
[5,] -8.936918e-05 -1.706490e-08 -4.966599e-05 -5.052466e-07  9.255947e-04
[6,]  6.248662e-05  2.917260e-09 -1.433516e-05 -7.933019e-07 -3.801628e-05
[7,] -6.756004e-10  2.123068e-13  3.881538e-10  9.565738e-12  4.789404e-10
              [,6]          [,7]
[1,]  6.

In [40]:
# convert W back to python (row major flattening)

# concatenate W
W <- do.call(rbind, res$W)
# W is transposed compared to paper
cat("import numpy as np\n\n")
cat("W_flat = np.array([", paste(c(W), collapse=",", sep=""), "])\n", sep="")
cat("W = W_flat.reshape((", ncol(W), ",", nrow(W), "))\n", sep = "")

import numpy as np

W_flat = np.array([-0.00222951618110004,-0.0016731503112262,-0.000712712683069581,-0.000559067705071171,0.000843143063159584,-0.0027715581933162,0.000664923143382163,-0.00075440164925469,-0.000766137002576692,0.00176939043578268,0.0387371356401894,0.155732298145699,0.850412370274383,-0.250942954549825,0.513015848499748,0.367837342945013,-1.1784485302149,0.407534443229021,-0.13878197828696,0.297686308772022,0.000406509087364554,-0.00119629053010869,0.0027865253870796,-0.00155988509374789,-0.000363053133169247,-0.000242919814505641,0.000638597853722288,-0.000486149491394773,-0.00134105941181399,0.00111455073454708,-0.0224396744104221,-0.526648924162047,-0.549016008459431,-0.0948710487551294,0.221829864790839,-0.0517573442567625,-0.0454927356053818,0.0782420391744516,-0.0856605195063234,-0.617449806109727,0.566921641619626,-0.174992437803256,0.597062958053762,1.45685234494226,0.264648961080451,-0.674422292306265,0.320225492201057,-0.740900005392962,-0.694832773944002,-