In [56]:
# import GFA code and data Y, parameters from test data
source("CCAGFA.R")
source("data.r")

# data Y, factors K and rank R now available

In [57]:
# set parameters to GFA
opts <- getDefaultOpts()
opts$R <- R
opts$dropK <- FALSE

In [58]:
# run
GFA(Y, K, opts)

[1] "The rank corresponds to full rank solution."
[1] "Iteration: 1 / cost: -40345.1976301884 / K 7"
[1] "Iteration: 2 / cost: -18272.1881654483 / K 7"
[1] "Iteration: 3 / cost: -18134.8283997095 / K 7"
[1] "Iteration: 4 / cost: -18118.9170062952 / K 7"
[1] "Iteration: 5 / cost: -18110.7290341416 / K 7"
[1] "Iteration: 6 / cost: -18104.9037753501 / K 7"
[1] "Iteration: 7 / cost: -18100.1310790101 / K 7"
[1] "Iteration: 8 / cost: -18096.3079456729 / K 7"
[1] "Iteration: 9 / cost: -18093.2212505553 / K 7"
[1] "Iteration: 10 / cost: -18090.7268053577 / K 7"
[1] "Iteration: 11 / cost: -18088.9563215361 / K 7"
[1] "Iteration: 12 / cost: -18087.7542804376 / K 7"
[1] "Iteration: 13 / cost: -18086.8330304066 / K 7"
[1] "Iteration: 14 / cost: -18086.0006894389 / K 7"
[1] "Iteration: 15 / cost: -18085.1578246154 / K 7"
[1] "Iteration: 16 / cost: -18084.208551968 / K 7"
[1] "Iteration: 17 / cost: -18083.0579209415 / K 7"
[1] "Iteration: 18 / cost: -18081.6806001779 / K 7"
[1] "Iteration: 19 / cos

$W
$W[[1]]
               [,1]          [,2]          [,3]          [,4]          [,5]
 [1,] -1.370748e-68  1.853028e-70 -2.994882e-81 -1.757069e-54  6.149663e-82
 [2,]  7.193003e-67  1.777789e-68 -2.642998e-79 -1.635084e-52 -1.661889e-79
 [3,] -3.752423e-67 -8.740577e-69  1.300670e-79  8.044962e-53  8.015635e-80
 [4,] -5.594415e-67 -1.491004e-68  2.217661e-79  1.371481e-52  1.388369e-79
 [5,]  2.236661e-67  4.848332e-69 -7.230554e-80 -4.464446e-53 -4.240434e-80
 [6,] -1.919179e-67 -2.508883e-69  3.744490e-80  2.309659e-53  1.987963e-80
 [7,] -1.059084e-68 -5.869554e-70  8.760369e-81  5.406671e-54  5.539373e-81
 [8,] -1.289823e-67 -2.809679e-69  4.175063e-80  2.582397e-53  2.606203e-80
 [9,] -6.727630e-67 -1.654177e-68  2.459851e-79  1.521401e-52  1.537037e-79
[10,] -1.034810e-67 -2.519790e-69  3.745017e-80  2.316624e-53  2.357890e-80
               [,6]          [,7]
 [1,]  1.449217e-81 -8.650650e-83
 [2,] -5.786076e-80  3.295016e-80
 [3,]  2.382668e-80 -1.576388e-80
 [4,]  4.944738e-80 -2.758754e-80
 [5,] -1.144308e-80  8.392969e-81
 [6,]  1.772763e-81 -3.880513e-81
 [7,]  2.222752e-81 -1.136215e-81
 [8,]  9.104524e-81 -5.186597e-81
 [9,]  5.332835e-80 -3.052971e-80
[10,]  8.513989e-81 -4.691095e-81

$W[[2]]
               [,1]          [,2]          [,3]          [,4]          [,5]
 [1,]  5.597726e-67  1.171516e-68 -1.547262e-79 -8.113362e-53 -8.941577e-80
 [2,] -3.612331e-67 -1.160112e-68  1.532114e-79  8.047186e-53  9.276407e-80
 [3,] -1.886087e-66 -4.679590e-68  6.171866e-79  3.240801e-52  3.715427e-79
 [4,]  5.448128e-67  8.543588e-69 -1.127538e-79 -5.919459e-53 -6.384537e-80
 [5,] -3.040801e-67 -9.402096e-69  1.237643e-79  6.512938e-53  8.075379e-80
 [6,] -1.130541e-66 -2.776782e-68  3.661788e-79  1.922753e-52  2.200639e-79
 [7,]  3.118613e-67  9.331513e-69 -1.235157e-79 -6.472727e-53 -7.041172e-80
 [8,] -9.582155e-67 -2.432713e-68  3.214387e-79  1.685878e-52  1.858164e-79
 [9,]  1.368980e-67  3.038336e-69 -4.043706e-80 -2.115853e-53 -1.997286e-80
[10,]  1.381698e-66  3.034533e-68 -4.005783e-79 -2.101746e-52 -2.319504e-79
               [,6]          [,7]
 [1,] -3.611023e-80  2.030992e-80
 [2,]  3.625655e-80 -2.054580e-80
 [3,]  1.582437e-79 -8.343566e-80
 [4,] -1.645054e-80  1.414870e-80
 [5,]  3.793979e-80 -1.801065e-80
 [6,]  9.376515e-80 -4.946227e-80
 [7,] -2.681107e-80  1.585412e-80
 [8,]  7.316225e-80 -4.171698e-80
 [9,]  8.651528e-83  4.331668e-81
[10,] -8.848727e-80  5.207832e-80

$W[[3]]
               [,1]          [,2]          [,3]          [,4]          [,5]
 [1,]  2.037228e-62  2.308497e-64 -2.921375e-75 -2.047138e-48 -1.741785e-75
 [2,]  2.459759e-62  3.790828e-64 -4.772834e-75 -3.352182e-48 -3.142244e-75
 [3,] -7.681759e-62 -1.556275e-63  1.963739e-74  1.377150e-47  1.254657e-74
 [4,]  2.033438e-62  4.863510e-64 -6.137064e-75 -4.304375e-48 -3.985929e-75
 [5,] -2.283114e-62 -5.342900e-64  6.740993e-75  4.731262e-48  4.405287e-75
 [6,]  1.291824e-61  2.511738e-63 -3.168041e-74 -2.222157e-47 -2.039458e-74
 [7,] -6.072674e-62 -9.798178e-64  1.235423e-74  8.666292e-48  7.898188e-75
 [8,] -2.722108e-63 -4.107680e-65  5.331939e-76  3.698044e-49  1.789422e-76
 [9,]  8.717345e-62  1.448273e-63 -1.829027e-74 -1.281747e-47 -1.139848e-74
[10,] -8.439402e-62 -1.611305e-63  2.033827e-74  1.425964e-47  1.289186e-74
               [,6]          [,7]
 [1,] -2.312935e-76  3.153508e-76
 [2,] -9.907601e-76  5.821686e-76
 [3,]  4.050467e-75 -2.332249e-75
 [4,] -1.398029e-75  7.442275e-76
 [5,]  1.432061e-75 -8.133265e-76
 [6,] -6.731802e-75  3.799132e-75
 [7,]  2.435144e-75 -1.469074e-75
 [8,] -1.927550e-76 -2.388205e-77
 [9,] -3.291371e-75  2.120966e-75
[10,]  3.994540e-75 -2.397687e-75


$covW
$covW[[1]]
               [,1]           [,2]           [,3]           [,4]           [,5]
[1,]   1.407392e-04 -4.537919e-135  3.730792e-146  2.465533e-119  1.708268e-146
[2,] -4.537919e-135   1.103777e-04  -6.355207e-20   4.080520e-20   9.745256e-19
[3,]  3.730792e-146  -6.355207e-20   1.376341e-04   1.562633e-33   1.540318e-20
[4