In [63]:
# import GFA code and data Y, parameters from test data
source("CCAGFA.R")
source("data.r")

# data Y, factors K and rank R now available

In [64]:
# set parameters to GFA
opts <- getDefaultOpts()
opts$R <- 3
opts$dropK <- FALSE

In [65]:
# run
GFA(Y, K, opts)

[1] "Warning: The data does not have zero mean."
[1] "NOTE: Optimization of the rotation is not supported for low rank model."
[1] "Iteration: 1 / cost: -41028.0020141636 / K 7"
[1] "Iteration: 2 / cost: -19083.2157889633 / K 7"
[1] "Iteration: 3 / cost: -18881.0188160493 / K 7"
[1] "Iteration: 4 / cost: -18864.2669622596 / K 7"
[1] "Iteration: 5 / cost: -18855.4858809611 / K 7"
[1] "Iteration: 6 / cost: -18847.2549546252 / K 7"
[1] "Iteration: 7 / cost: -18839.654307275 / K 7"
[1] "Iteration: 8 / cost: -18833.3834025142 / K 7"
[1] "Iteration: 9 / cost: -18828.6028307889 / K 7"
[1] "Iteration: 10 / cost: -18824.9545975893 / K 7"
[1] "Iteration: 11 / cost: -18822.0500745983 / K 7"
[1] "Iteration: 12 / cost: -18819.7202214646 / K 7"
[1] "Iteration: 13 / cost: -18817.9815618223 / K 7"
[1] "Iteration: 14 / cost: -18816.716933128 / K 7"
[1] "Iteration: 15 / cost: -18815.7321746166 / K 7"
[1] "Iteration: 16 / cost: -18814.9319706757 / K 7"
[1] "Iteration: 17 / cost: -18814.25803456 / K 7"
[1

$W
$W[[1]]
                [,1]          [,2]          [,3]          [,4]          [,5]
 [1,]  -3.850376e-99 -3.023099e-95  1.802397e-98 -7.710099e-90  5.656060e-98
 [2,]  -3.586037e-99 -1.885885e-94  8.417198e-98 -4.064108e-89  3.728093e-97
 [3,]  5.453138e-100  1.233950e-94 -5.267589e-98  2.584739e-89 -2.458592e-97
 [4,]  5.362106e-100 -1.858093e-94  7.748498e-98 -3.838447e-89  3.715503e-97
 [5,]  -1.252333e-99  1.399984e-95 -4.210188e-99  2.401285e-90 -2.921450e-98
 [6,]  -1.857272e-99  1.002349e-95 -1.638180e-99  1.415742e-90 -2.181903e-98
 [7,]  -2.049780e-99 -1.258014e-94  5.582998e-98 -2.684050e-89  2.492243e-97
 [8,]   3.348066e-99 -3.322731e-95  9.318749e-99 -5.712743e-90  6.968123e-98
 [9,]   1.511479e-99  2.338028e-94 -1.005071e-97  4.911216e-89 -4.653005e-97
[10,]  -2.255385e-99  5.602979e-95 -2.053378e-98  1.075066e-89 -1.142193e-97
               [,6]           [,7]
 [1,] -3.707755e-96  7.205077e-105
 [2,] -2.394273e-95  2.662079e-104
 [3,]  1.576222e-95 -1.582850e-104
 [4,] -2.380036e-95  2.262463e-104
 [5,]  1.855158e-96 -6.268373e-106
 [6,]  1.353162e-96  4.218654e-106
 [7,] -1.602571e-95  1.748919e-104
 [8,] -4.376398e-96  1.126432e-105
 [9,]  2.985600e-95 -3.042132e-104
[10,]  7.276836e-96 -4.963908e-105

$W[[2]]
                [,1]          [,2]           [,3]          [,4]           [,5]
 [1,] -1.028418e-101 -2.812811e-96   1.199258e-99 -5.867931e-91   5.599641e-99
 [2,] -2.904347e-101  2.920684e-96  -1.189365e-99  5.956647e-91  -5.856288e-99
 [3,] -6.774465e-101 -1.924042e-96  9.017250e-100 -4.259780e-91   3.767068e-99
 [4,]  3.590773e-101  5.224536e-96  -2.249005e-99  1.097827e-90  -1.038884e-98
 [5,] -3.091625e-101  3.434155e-96  -1.399832e-99  7.045195e-91  -6.878888e-99
 [6,] -3.191763e-101 -3.677051e-96   1.593976e-99 -7.732177e-91   7.306315e-99
 [7,]  2.417893e-101 -1.770857e-96  7.142250e-100 -3.567017e-91   3.560840e-99
 [8,]  5.708497e-103  2.723462e-97 -1.126572e-100  5.939460e-92 -5.387204e-100
 [9,] -5.475241e-101  3.751336e-97 -8.161789e-101  5.832716e-92 -7.973305e-100
[10,]  1.205062e-100  4.991094e-96  -2.267826e-99  1.080055e-90  -9.834678e-99
               [,6]           [,7]
 [1,] -3.597718e-97  3.586664e-106
 [2,]  3.749418e-97 -3.368483e-106
 [3,] -2.429834e-97  2.990869e-106
 [4,]  6.671263e-97 -6.812910e-106
 [5,]  4.399269e-97 -3.982032e-106
 [6,] -4.697542e-97  4.858253e-106
 [7,] -2.281452e-97  1.989526e-106
 [8,]  3.407601e-98 -3.365691e-107
 [9,]  5.005581e-98  2.914139e-108
[10,]  6.338742e-97 -7.277573e-106

$W[[3]]
                [,1]          [,2]           [,3]          [,4]           [,5]
 [1,] -3.368169e-102 -5.349006e-98  2.704051e-101 -1.247029e-92  1.032960e-100
 [2,] -4.688590e-103 -9.242519e-98  3.939871e-101 -1.952150e-92  1.839090e-100
 [3,]  5.923561e-103 -2.540746e-97  1.058887e-100 -5.278238e-92  5.074217e-100
 [4,] -1.658180e-102 -2.958344e-97  1.265597e-100 -6.230479e-92  5.886609e-100
 [5,]  1.400163e-103 -1.731291e-98  6.989614e-102 -3.640695e-93  3.459797e-101
 [6,] -5.244649e-102 -3.403977e-97  1.501898e-100 -7.295034e-92  6.738061e-100
 [7,]  4.331991e-102 -5.135525e-98  1.560905e-101 -9.094160e-93  1.066944e-100
 [8,] -3.308762e-102 -2.421897e-97  1.061654e-100 -5.185746e-92  4.798071e-100
 [9,]  2.620965e-102  1.309045e-97 -5.850744e-101  2.835455e-92 -2.582668e-100
[10,]  1.892294e-102  5.521917e-98 -2.574092e-101  1.227779e-92 -1.082938e-100
               [,6]           [,7]
 [1,] -6.675910e-99  9.635442e-108
 [2,] -1.176567e-98  1.187703e-107
 [3,] -3.246829e-98  3.099124e-107
 [4,] -3.771650e-98  3.820363e-107
 [5,] -2.193708e-99  2.002869e-108
 [6,] -4.325428e-98  4.692305e-107
 [7,] -6.738961e-99  2.491952e-108
 [8,] -3.076251e-98  3.298935e-107
 [9,]  1.658642e-98 -1.855577e-107
[10,]  6.958743e-99 -8.536474e-108

$W[[4]]
                [,1]          [,2]           [,3]          [,4]           [,5]
 [1,]  7.595819e-102  1.154020e-96 -4.967491e-100  2.419757e-91  -2.296055e-99
 [2,] -2.746502e-102 -4.907068e-97  2.106853e-100 -1.025925e-91 