In [69]:
import importlib
import gfa
importlib.reload(gfa)

<module 'gfa' from '/Users/axelri/Dropbox/kth/aml/project/src/gfa.py'>

In [70]:
import numpy as np
dims = 10
samples = 100
X = np.random.randn(dims, samples)
D = np.array([3,4,3])

In [71]:
g = gfa.GFA(optimize_method="BFGS", debug=True)
g.fit(X,D)

Values before
U:
 [[ 5.3529667  -5.95088825  2.69355465 -2.31888228]
 [ 3.54101687  1.44481419  0.2827171  -4.00330367]
 [ 0.20239487 -1.57288958 -0.28735205  0.48766566]]
V:
 [[ 5.3529667  -5.95088825  2.69355465 -2.31888228]
 [ 3.54101687  1.44481419  0.2827171  -4.00330367]
 [ 0.20239487 -1.57288958 -0.28735205  0.48766566]]
mu_u
 [[ 0.]
 [ 0.]
 [ 0.]]
mu_v
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
Ln alpha
 [[-24.04948566  12.87971702  -4.16933082 -19.82398133  17.4047901
   48.06721184  -5.17500284]
 [ 23.73435827  12.71182567   3.55702048 -18.68769124  -2.63051762
   -2.62084895 -21.02081206]
 [ -9.83336797  -0.26425247  -1.6339383    2.38597949   5.05173519
    7.94113177   1.54714773]]
Objective eval:
Bound: -17.010639130206993
Ln alpha:
[[-24.04948566  12.87971702  -4.16933082 -19.82398133  17.4047901
   48.06721184  -5.17500284]
 [ 23.73435827  12.71182567   3.55702048 -18.68769124  -2.63051762
   -2.62084895 -21.02081206]
 [ -9.83336797  -0.26425247  -1.6339383    2

/Users/axelri/Dropbox/kth/aml/project/src/gfa.py:122: RuntimeWarning: overflow encountered in exp
  
/Users/axelri/Dropbox/kth/aml/project/src/gfa.py:99: RuntimeWarning: overflow encountered in exp
  
/Users/axelri/Dropbox/kth/aml/project/src/gfa.py:122: RuntimeWarning: overflow encountered in exp
  


In [43]:
res = g.update_alpha()

Bound: 427.84698612566683
Bound: inf
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: nan
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
Bound: inf
         Current function value: 427.846986
         Iterations: 0
         Function evaluations: 43
         Gradient evaluations: 31
Values
U:
 [[ 1.67930165  3.67893068  0.35318465  2.77527846]
 [-3.67842553 -3.03619593  0.1281424   0.68770463]
 [ 1.00789451 -5.4248537  -0.3884013   1.94407707]]
V:
 [[ 1.67930165  3.67893068  0.35318465  2.77527846]
 [-3.67842553 -3.03619593  0.1281424   0.68770463]
 [ 1.00789451 -5.4248537  -0.3884013   1.94407707]]
mu_u
 [[ 0.]
 [ 0.]
 [ 0.]]
mu_v
 [[ 0.]
 [ 0.]
 [ 0.]

/Users/axelri/Dropbox/kth/aml/project/src/gfa.py:122: RuntimeWarning: overflow encountered in exp
  
/Users/axelri/Dropbox/kth/aml/project/src/gfa.py:99: RuntimeWarning: overflow encountered in exp
  
/Users/axelri/Dropbox/kth/aml/project/src/gfa.py:122: RuntimeWarning: overflow encountered in exp
  


In [44]:
# optimizer messages
res

      fun: 427.84698612566683
 hess_inv: array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])
      jac: array([  1.65150686e+06,   3.39070493e+06,  -1.95199474e+06,
        -2.05306720e+06,  -4.17866957e+04,  -2.23943925e+04,
         1.65252634e+04,   3.33141975e+04,  -1.02145766e+05,
        -6.94984453e+05,   5.07682821e+05,   1.94564730e+05,
         2.75238431e+05,  -1.66813419e+06,  -1.16608771e+05,
         5.94515696e+05,   6.44902189e+00,   1.73580516e+01,
        -4.81243331e-01,  -1.64039161e+01,   3.12836550e+03,
        -1.67853356e+04,  -1.20329448e+03,   6.00538718e+03,
         3.67607787e+01,   8.36402956e+01,   6.50972302e+00,
         3.34918753e+01,   2.53461007e+05,   5.55271955e+05,
         5.33053256e+04,   4.18852352e+05,  -6.49646935e+04,
        -5.36519915e+04,   2.26088014e+03,   1.21477384e+04,
         8